#!/command/with-contenv bash
s6-svc -O /run/service/startup

if [[ "$USE_PAWNSAPP" != "n" ]]
then
    s6-svc -u /run/service/pawnsapp
fi

if [[ "$USE_HONEYGAIN" != "n" ]]
then
    s6-svc -u /run/service/honeygain
fi

if [[ "$USE_HONEYGAIN_AUTOCLAIM" != "n" ]]
then
    s6-svc -u /run/service/honeygain-autoclaim
fi

if [[ "$USE_EARNAPP" != "n" ]]
then
    s6-svc -u /run/service/earnapp
    s6-svc -u /run/service/earnapp-log2ram
fi

sleep 5